### ISSUE TITLE
Query failure/success dependent only on orderBy direction

### ISSUE THREAD

**Issue by thephez** [dashevo/rs-drive#83]
## Expected Behavior

Query would succeed or fail consistently regardless of `orderBy` direction (`asc` vs `desc`).

## Current Behavior

The same query succeeds when the `orderBy` direction is `desc` and fails with the following error when the direction is `asc`:
`InvalidRequestError: Invalid query: path_queries can only refer to items and references`

Edit: Upon further testing, it appears that this affects both `<` and `<=` operators for the specified query. The issue did not present itself when using `>` or `>=` operators for this query.

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Run the query below with `orderBy: [['records.dashUniqueIdentityId', 'desc']],`
2. Get successful response
3. Change to `orderBy: [['records.dashUniqueIdentityId', 'asc']],`
4. Get `InvalidRequestError` error

```js
client.platform.documents.get(
  'dpns.domain',
  {
    limit: 2,
    where: [
      ['records.dashUniqueIdentityId', '<=', 'FETe2GxdRsAUj8Qoy3tsr6J822aupG5VYtetoYBgXt5P'],
    ],
    orderBy: [['records.dashUniqueIdentityId', 'desc']],
  },
);
```

## Your Environment

* Version used: Dash SDK v3.22.0-dev.8 or 14 (only versions tried)
* Environment name and version (e.g. Chrome 39, node.js 5.4): Krupnik devnet
* Operating System and version (desktop, server, or mobile): Linux
* Link to your project: Example here: https://replit.com/@thephez/Query-syntax-comparison#index.js

**Comment by shumkov** [comment]
Fixed in v0.22-dev
