### ISSUE TITLE
Query responds with a number of documents > limit

### ISSUE THREAD

**Issue by thephez** [dashevo/rs-drive#85]
## Expected Behavior

Query should not return more records than the `limit`

## Current Behavior

In at least some situations it is possible to receive more than the expected limit of results. One case is demonstrated in the example below. The behavior is elicited simply by changing the `orderBy` direction. The same query responds correctly when the `orderBy` direction is `asc` and returns excess results when the direction is `desc`.

I only tried this with `startAt`, but presume it affects `startAfter` and possibly others.

## Possible Solution

N/A, but _possibly_ related to #83 which also shows up depending on `orderBy`. But really no idea :man_shrugging: :slightly_smiling_face: 

## Steps to Reproduce (for bugs)

1. Run the query below with `orderBy: [['normalizedLabel', 'asc']],`
2. Get successful response limited to 1 document
3. Change to `orderBy: [['normalizedLabel', 'desc']],`
4. Get incorrect response containing (atm) 13 documents

```js
client.platform.documents.get(
    'dpns.domain',
    {
      limit: 1,
      startAt: Buffer.from(Identifier.from('4Qp3menV9QjE92hc3BzkUCusAmHLxh1AU6gsVsPF4L2q')),
      where: [
        ['normalizedParentDomainName', '==', 'dash'],
        ['normalizedLabel', 'startsWith', 'RT-'.toLowerCase()],
      ],
      orderBy: [['normalizedLabel', 'asc']],
    },
  )
```

## Your Environment

* Version used: Dash SDK v3.22.0-dev.8 or 14 (only versions tried)
* Environment name and version (e.g. Chrome 39, node.js 5.4): Krupnik devnet
* Operating System and version (desktop, server, or mobile): Linux
* Link to your project: Example here: https://replit.com/@thephez/Query-syntax-v022-limit-issue#index.js

**Comment by QuantumExplorer** [comment]
Thanks @thephez, this is now fixed in GroveDB https://github.com/dashevo/grovedb/pull/88
